services:
  db:
    image: mysql:8.0-oracle
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootd
    ports:
      - "3306:3306"
    volumes:
      - krlsnathaan_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  krlsnathaan_data: